name: patreon-ci

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: ci-lint project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v2
  test:
    name: ci-test project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - run: make generate-api
      - run: make run-coverage
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#      - name: Login to DockerHub Registry
#        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
#      - name: Build Docker image
#        run: sudo docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/sessions-service:latest -f ./docker/sessions-service.Dockerfile . &&
#          sudo docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/files-service:latest -f ./docker/files-service.Dockerfile . &&
#          sudo docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/main:latest -f ./docker/builder.Dockerfile .
#
#      - name: Push the image
#        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/sessions-service:latest &&
#          docker push ${{ secrets.DOCKERHUB_USERNAME }}/files-service:latest &&
#          docker push ${{ secrets.DOCKERHUB_USERNAME }}/main:latest
#
#  deploy:
#    runs-on: ubuntu-latest
#    needs: build
#    steps:
#      - name: pull project
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.USER }}
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          script: cd 2021_2_Pyaterochka/ && sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/sessions-service:latest &&
#            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/files-service:latest &&
#            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/main:latest
#      - name: run project
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.USER }}
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          script: ls && cd 2021_2_Pyaterochka/ && sudo make run-https
#
#
